### ISSUE TITLE
Morning code review 23/07/2021

### ISSUE THREAD

**Issue by notlfish** [petumazo/Household-Expenses#1]

**Comment by enionsouza** [comment]
Great job so far, @petumazo! Keep it up! 💯 
Just to stick to the ERD required by the project's specs, my suggestion would be to use `has_and_belongs_to_many` association for `groups` and `expenses` tables...

**Comment by petudeveloper** [comment]
Thanks @enionsouza for the feedback and for taking the time to come and comment. I will follow your suggestion and apply a many-to-many connection, but I will use the `has_many :through` Association.
