### ISSUE TITLE
#Team-208-the-sargas P2P Code Review

### ISSUE THREAD

**Issue by enionsouza** [petumazo/Household-Expenses#9]
Excellent job so far, @petumazo!
Your visual design looks great! A real mobile app look!

**Comment by notlfish** [comment]
Nice job! Do take care of your branches and pull requests. Remember that pull request messages should be much more descriptive than commit messages.

**Comment by petudeveloper** [comment]
@notlfish @enionsouza Thanks for the comments, I have been working and improving my pull requests and branches names and descriptions.
